spring.application.name=SpringBootMVC

spring.datasource.url=jdbc:postgresql://localhost:5432/traineeDB
spring.datasource.username=username
spring.datasource.password=password

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8085
